<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SpeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('species')->insert([
            // Marine Mammals
            [
                'name' => 'Dugong',
                'scientific_name' => 'Dugong dugon',
                'common_name' => 'Sea Cow',
                'local_name' => 'Baboy-Dagat',
                'category' => 'marine_mammals',
                'description' => 'A herbivorous marine mammal that grazes on seagrass.',
                'conservation_status' => 'VU',
                'shape' => 'dugong-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spinner Dolphin',
                'scientific_name' => 'Stenella longirostris',
                'common_name' => 'Spinner Dolphin',
                'local_name' => 'Lumad',
                'category' => 'marine_mammals',
                'description' => 'A small, acrobatic dolphin known for its spinning leaps.',
                'conservation_status' => 'LC',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bryde’s Whale',
                'scientific_name' => 'Balaenoptera edeni',
                'common_name' => 'Bryde’s Whale',
                'local_name' => 'Balyena',
                'category' => 'marine_mammals',
                'description' => 'A baleen whale found in warm seas, known for its sleek body.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sperm Whale',
                'scientific_name' => 'Physeter macrocephalus',
                'common_name' => 'Sperm Whale',
                'local_name' => 'Balyenang Espada',
                'category' => 'marine_mammals',
                'description' => 'The largest toothed predator, found in deep ocean habitats.',
                'conservation_status' => 'VU',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Irrawaddy Dolphin',
                'scientific_name' => 'Orcaella brevirostris',
                'common_name' => 'Irrawaddy Dolphin',
                'local_name' => 'Lampas-Lampas',
                'category' => 'marine_mammals',
                'description' => 'A small dolphin found in coastal waters and river mouths.',
                'conservation_status' => 'EN',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Marine Turtles
            [
                'name' => 'Green Sea Turtle',
                'scientific_name' => 'Chelonia mydas',
                'common_name' => 'Green Turtle',
                'local_name' => 'Pawikan',
                'category' => 'marine_turtles',
                'description' => 'A large sea turtle with a greenish shell. Found in shallow lagoons and seagrass beds.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hawksbill Turtle',
                'scientific_name' => 'Eretmochelys imbricata',
                'common_name' => 'Hawksbill',
                'local_name' => 'Pawikan',
                'category' => 'marine_turtles',
                'description' => 'A critically endangered sea turtle with a distinctive beak-like jaw.',
                'conservation_status' => 'CR',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olive Ridley Turtle',
                'scientific_name' => 'Lepidochelys olivacea',
                'common_name' => 'Olive Ridley',
                'local_name' => 'Pawikan',
                'category' => 'marine_turtles',
                'description' => 'A small sea turtle known for its mass nesting behavior.',
                'conservation_status' => 'VU',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Loggerhead Turtle',
                'scientific_name' => 'Caretta caretta',
                'common_name' => 'Loggerhead',
                'local_name' => 'Pawikan',
                'category' => 'marine_turtles',
                'description' => 'A large-headed sea turtle with a reddish-brown shell.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leatherback Turtle',
                'scientific_name' => 'Dermochelys coriacea',
                'common_name' => 'Leatherback',
                'local_name' => 'Pawikan',
                'category' => 'marine_turtles',
                'description' => 'The largest sea turtle, with a leathery shell and a cosmopolitan distribution.',
                'conservation_status' => 'VU',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sharks and Rays
            [
                'name' => 'Whale Shark',
                'scientific_name' => 'Rhincodon typus',
                'common_name' => 'Butanding',
                'local_name' => 'Butanding',
                'category' => 'sharks_rays',
                'description' => 'The largest known fish species. A filter feeder that is harmless to humans.',
                'conservation_status' => 'EN',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manta Ray',
                'scientific_name' => 'Manta birostris',
                'common_name' => 'Manta Ray',
                'local_name' => 'Pagi',
                'category' => 'sharks_rays',
                'description' => 'A large ray with triangular pectoral fins, known for its graceful swimming.',
                'conservation_status' => 'VU',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Great Hammerhead Shark',
                'scientific_name' => 'Sphyrna mokarran',
                'common_name' => 'Hammerhead Shark',
                'local_name' => 'Pating',
                'category' => 'sharks_rays',
                'description' => 'A large shark with a distinctive hammer-shaped head.',
                'conservation_status' => 'CR',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue Shark',
                'scientific_name' => 'Prionace glauca',
                'common_name' => 'Blue Shark',
                'local_name' => 'Pating Asul',
                'category' => 'sharks_rays',
                'description' => 'A sleek and fast-swimming shark with a blue hue.',
                'conservation_status' => 'NT',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thresher Shark',
                'scientific_name' => 'Alopias vulpinus',
                'common_name' => 'Thresher Shark',
                'local_name' => 'Pating Lawin',
                'category' => 'sharks_rays',
                'description' => 'A shark known for its long tail used to stun prey.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
