<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SpeciesSeeder extends Seeder
{

    public function run(): void
    {
        //
        DB::table('species')->insert([
            [
                // Marine Mammals
                'name' => 'Bryde’s whale',
                'scientific_name' => 'Balaenoptera edeni',
                'common_name' => 'Bryde’s whale',
                'local_name' => 'Balyena',
                'category' => 'marine_mammals',
                'description' => 'Bryde’s Whale has a pointed head with three distinct ridges on the rostrum, a tall falcate dorsal fin, and grows to 11.5–14.5 meters in length.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Omura’s whale',
                'scientific_name' => 'Balaenoptera omurai',
                'common_name' => 'Omura’s whale',
                'local_name' => 'Balyenang Omura',
                'category' => 'marine_mammals',
                'description' => 'Omura’s Whale is a relatively small baleen whale (up to 11.5 m) with a single ridge on the rostrum, asymmetrical jaw coloration (white on the right, dark on the left), and a tall dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue whale',
                'scientific_name' => 'Balaenoptera musculus',
                'common_name' => 'Blue whale',
                'local_name' => 'Asul na Balyena',
                'category' => 'marine_mammals',
                'description' => 'Blue Whale is the largest animal on Earth, reaching up to 33 meters long, with a broad U-shaped head, a single ridge, and a small dorsal fin far back on its body.',
                'conservation_status' => 'EN',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Humpback whale',
                'scientific_name' => 'Megaptera novaeangliae',
                'common_name' => 'Humpback whale',
                'local_name' => 'Balyenang kuba',
                'category' => 'marine_mammals',
                'description' => 'Humpback Whale grows to 11.5–15 meters long and is known for its long flippers, knobby head with a median ridge, and a notched fluke with varying color patterns.',
                'conservation_status' => 'LC',
                'shape' => 'whale-like',
                'is_dangerous' => false,
            'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'Pygmy killer whale',
                'scientific_name' => 'Feresa attenuata',
                'common_name' => 'Pygmy killer whale',
                'local_name' => 'Maliit na mamamatay na balyena',
                'category' => 'marine_mammals',
                'description' => 'Pygmy Killer Whale is 2.1 to 2.6 meters long, with a rounded head, dark coloration, white lips, and a tall slightly falcate dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'Short-finned pilot whale',
                'scientific_name' => 'Globicephala macrorhynchus',
                'common_name' => 'Short-finned pilot whale',
                'local_name' => 'Balyenang piloto',
                'category' => 'marine_mammals',
                'description' => 'Short-finned Pilot Whale measures 3.6 to 6.5 meters, has a robust body, a blunt square-shaped head, and a very falcate dorsal fin with a broad base.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Risso’s dolphin',
                'scientific_name' => 'Grampus griseus',
                'common_name' => 'Risso’s dolphin',
                'local_name' => 'Lumba-lumbang Risso',
                'category' => 'marine_mammals',
                'description' => 'Risso’s Dolphin is 2.6 to 3.8 meters long, with a rounded head, V-shaped crease, tall slightly falcate dorsal fin, and white scarring over a gray body.',
                'conservation_status' => 'LC',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fraser’s dolphin',
                'scientific_name' => 'Lagenodelphis hosei',
                'common_name' => 'Fraser’s dolphin',
                'local_name' => 'Lumba-lumbang Fraser',
                'category' => 'marine_mammals',
                'description' => 'Fraser’s Dolphin grows between 2 and 2.6 meters, has a defined beak, short pectoral fins, a triangular dorsal fin, and a dark facial stripe running to the anus.',
                'conservation_status' => 'LC',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Irrawaddy dolphin',
                'scientific_name' => 'Orcaella brevirostris',
                'common_name' => 'Irrawaddy dolphin',
                'local_name' => 'Lumba-lumbang Irrawaddy',
                'category' => 'marine_mammals',
                'description' => 'Irrawaddy Dolphin measures 2.1 to 2.6 meters, has a round head with no beak, a flexible neck, small rounded dorsal fin, and rounded flippers.',
                'conservation_status' => 'CR',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Killer whale',
                'scientific_name' => 'Orcinus orca',
                'common_name' => 'Killer whale',
                'local_name' => 'Orca',
                'category' => 'marine_mammals',
                'description' => 'Killer Whale is a large dolphin 5.5 to 9.8 meters long, with a black-and-white body pattern, a tall dorsal fin (especially in males), and a prominent eye patch and saddle.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Melon-headed whale',
                'scientific_name' => 'Peponocephala electra',
                'common_name' => 'Melon-headed whale',
                'local_name' => 'Balyenang melon-head',
                'category' => 'marine_mammals',
                'description' => 'Melon-headed Whale is 2.1 to 2.7 meters long, with a triangular head, no beak, dark gray to black coloration, white lips, and a tall slightly falcate dorsal fin.',
                'conservation_status' => 'LC',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'False killer whale',
                'scientific_name' => 'Pseudorca crassidens',
                'common_name' => 'False killer whale',
                'local_name' => 'Yamang-dagat na Mammal',
                'category' => 'marine_mammals',
                'description' => 'The False Killer Whale is a large, dark gray dolphin with no beak, a rounded head, long flippers, and a tall dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gray’s spinner dolphin',
                'scientific_name' => 'Stenella longirostris longirostris',
                'common_name' => 'Gray’s spinner dolphin',
                'local_name' => 'Lumba-lumbang Gray',
                'category' => 'marine_mammals',
                'description' => 'Gray’s Spinner Dolphin is 1.3 to 2.1 meters long, slender, has a long thin black-tipped beak, a small triangular dorsal fin, and is highly acrobatic and commonly seen in the Philippines.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dwarf spinner dolphin',
                'scientific_name' => 'Stenella longirostris roseiventris',
                'common_name' => 'Dwarf spinner dolphin',
                'local_name' => 'Lumba-lumbang duwende',
                'category' => 'marine_mammals',
                'description' => 'Dwarf Spinner Dolphin is a smaller version (1.3 to 1.6 meters) of the spinner dolphin with large dorsal and pectoral fins and a falcate dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rough-toothed dolphin',
                'scientific_name' => 'Steno bredanensis',
                'common_name' => 'Rough-toothed dolphin',
                'local_name' => 'Lumba-lumbang magaspang angipin',
                'category' => 'marine_mammals',
                'description' => 'Rough-toothed Dolphin is 2.1 to 2.6 meters long with a robust body, conical head, long beak with a smooth slope from the melon, and visible white markings on its lips and belly.',
                'conservation_status' => 'LC',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indo-Pacific bottlenose dolphin',
                'scientific_name' => 'Tursiops aduncus',
                'common_name' => 'Indo-Pacific bottlenose dolphin',
                'local_name' => 'Lumba-lumbang Indo-Pasipiko',
                'category' => 'marine_mammals',
                'description' => 'Indo-Pacific Bottlenose Dolphin is about 2.7 meters long, with a slender beak, less prominent melon crease, a tall slightly falcate dorsal fin, and belly spots in adults.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Common bottlenose dolphin',
                'scientific_name' => 'Tursiops truncatus',
                'common_name' => 'Common bottlenose dolphin',
                'local_name' => 'Karaniwang lumba-lumba',
                'category' => 'marine_mammals',
                'description' => 'Common Bottlenose Dolphin ranges from 1.9 to 3.8 meters, has a large robust body, a stocky beak with a prominent crease, and a tall falcate dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pygmy sperm whale',
                'scientific_name' => 'Kogia breviceps',
                'common_name' => 'Pygmy sperm whale',
                'local_name' => 'Maliit na balyenang tamod',
                'category' => 'marine_mammals',
                'description' => 'Pygmy Sperm Whale is 2.3 to 3.4 meters long with a square-like head, narrow lower jaw, small rounded dorsal fin located far back, and a light-colored "false gill."',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dwarf sperm whale',
                'scientific_name' => 'Kogia sima',
                'common_name' => 'Dwarf sperm whale',
                'local_name' => 'Balyenang duwende (tamod)',
                'category' => 'marine_mammals',
                'description' => 'Dwarf Sperm Whale is 2.1 to 2.7 meters long, similar to the pygmy sperm whale but with a larger and more pointed dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sperm whale',
                'scientific_name' => 'Physeter macrocephalus',
                'common_name' => 'Sperm whale',
                'local_name' => 'Balyenang tamod',
                'category' => 'marine_mammals',
                'description' => 'Sperm Whale is 11 to 18 meters long, with a large blunt square-shaped head, left-positioned blowhole, small hump instead of dorsal fin, paddle-shaped pectorals, and a triangular fluke.',
                'conservation_status' => 'VU',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Longman’s beaked whale',
                'scientific_name' => 'Indopacetus pacificus',
                'common_name' => 'Longman’s beaked whale',
                'local_name' => 'Balyenang Longman',
                'category' => 'marine_mammals',
                'description' => 'Longman’s Beaked Whale ranges from 4 to 9 meters in length, has a tube-like beak, bulging forehead, falcate dorsal fin set midway, and V-shaped throat grooves.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blainville’s beaked whale',
                'scientific_name' => 'Mesoplodon densirostris',
                'common_name' => 'Blainville’s beaked whale',
                'local_name' => 'Balyenang Blainville',
                'category' => 'marine_mammals',
                'description' => 'Blainville’s Beaked Whale is 4.5 to 6 meters long, brownish to gray in color, with a small head, arched lower jaw with tusks, small dorsal fin, and narrow pectoral fins.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cuvier’s beaked whale',
                'scientific_name' => 'Ziphius cavirostris',
                'common_name' => 'Cuvier’s beaked whale',
                'local_name' => 'Balyenang Cuvier',
                'category' => 'marine_mammals',
                'description' => 'Cuvier’s Beaked Whale grows to 5.5–7 meters, lacks a distinct beak, has a stubby face, small falcate dorsal fin located three-fourths back, and rounded flippers.',
                'conservation_status' => 'LC',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                    'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ginkgo-toothed beaked whale',
                'scientific_name' => 'Mesoplodon ginkgodens',
                'common_name' => 'Ginkgo-toothed beaked whale',
                'local_name' => 'Balyenang gingko-tooth',
                'category' => 'marine_mammals',
                'description' => 'Ginkgo-toothed Beaked Whale is around 5.3 meters long, has a spindle-shaped body, small head, and a small dorsal fin two-thirds back on its body.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deraniyagala’s beaked whale',
                'scientific_name' => 'Mesoplodon hotaula',
                'common_name' => 'Deraniyagala’s beaked whale',
                'local_name' => 'Balyenang Deraniyagala',
                'category' => 'marine_mammals',
                'description' => 'Deraniyagala’s Beaked Whale is similar in appearance and size to the ginkgo-toothed beaked whale.',
                'conservation_status' => 'DD',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dugong',
                'scientific_name' => 'Dugong dugon',
                'common_name' => 'Dugong',
                'local_name' => 'Dugong / Baboy-dagat',
                'category' => 'marine_mammals',
                'description' => 'Dugong grows to 2.4 to 2.7 meters, has a rounded body without a dorsal fin, grayish coloration, armpit-located mammary glands, and nostrils slightly above the snout.',
                'conservation_status' => 'VU',
                'shape' => 'dugong-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fin whale',
                'scientific_name' => 'Balaenoptera physalus',
                'common_name' => 'Fin whale',
                'local_name' => 'Balyenang palikpik (Fin Whale)',
                'category' => 'marine_mammals',
                'description' => 'Fin Whale reaches 27 meters, has a V-shaped head with a single ridge, dark-colored body, and asymmetrical jaw coloration—dark left, white right.',
                'conservation_status' => 'EN',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Common minke whale',
                'scientific_name' => 'Balaenoptera acutorostrata',
                'common_name' => 'Common minke whale',
                'local_name' => 'Karaniwang Balyenang Minke',
                'category' => 'marine_mammals',
                'description' => 'Common Minke Whale is 6.5 to 8.8 meters long, has a sharply pointed head, a prominent median ridge, and a tall falcate dorsal fin two-thirds back on the body.',
                'conservation_status' => 'LC',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finless porpoise',
                'scientific_name' => 'Neophocaena phocaenoides',
                'common_name' => 'Finless porpoise',
                'local_name' => 'Lumba-lumbang walang palikpik',
                'category' => 'marine_mammals',
                'description' => 'Finless Porpoise reaches 2.27 meters, has no dorsal fin and a flexible neck and has a small cetacean with no dorsal fin, a rounded head, and a flexible neck.',
                'conservation_status' => 'VU',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indo-Pacific humpback dolphin',
                'scientific_name' => 'Sousa chinensis',
                'common_name' => 'Indo-Pacific humpback dolphin',
                'local_name' => 'Lumba-lumbang may umbok',
                'category' => 'marine_mammals',
                'description' => 'Indo-Pacific Humpback Dolphin is 2.6 to 2.8 meters long, has a beakless rounded head, dorsal fin on a noticeable hump, and calves that darken to pink as they mature.',
                'conservation_status' => 'NT',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sei whale',
                'scientific_name' => 'Balaenoptera borealis',
                'common_name' => 'Sei whale',
                'local_name' => 'Balyenang Sei',
                'category' => 'marine_mammals',
                'description' => 'Sei Whale is 12 to 17 meters long, with a pointed rostrum, single head ridge, and a steeply angled dorsal fin.',
                'conservation_status' => 'EN',
                'shape' => 'whale-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Long-beaked common dolphin',
                'scientific_name' => 'Delphinus capensis',
                'common_name' => 'Long-beaked common dolphin',
                'local_name' => 'Karaniwang lumba-lumbang mahabang nguso',
                'category' => 'marine_mammals',
                'description' => 'Long-beaked Common Dolphin is 2.6 meters long, with a long narrow beak, tall falcate dorsal fin, a crease between melon and beak, and an hourglass color pattern on its side.',
                'conservation_status' => 'DD',
                'shape' => 'dolphin-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // sharks and rays
            [
                'name' => 'Knifetooth sawfish',
                'scientific_name' => 'Anoxypristis cuspidata',
                'common_name' => 'Knifetooth sawfish',
                'local_name' => 'Espadang isda (Knifetooth)',
                'category' => 'sharks_rays',
                'description' => 'The Knifetooth Sawfish has a moderately slender body, a blade-like snout without teeth on the basal quarter, short-based pectoral fins, and a long lower lobe of the caudal fin. It can grow up to 4.7 meters.',
                'conservation_status' => 'EN',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Green sawfish',
                'scientific_name' => 'Pristis zijsron',
                'common_name' => 'Green sawfish',
                'local_name' => 'Espadang berde',
                'category' => 'sharks_rays',
                'description' => 'The Green Sawfish is a robust species with 24–28 unevenly spaced teeth starting near the base of its saw-like snout, a feeble lower caudal fin lobe, and broad-based pectoral fins. It grows up to 5 meters long.',
                'conservation_status' => 'CR',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Largetooth sawfish',
                'scientific_name' => 'Pristis pristis',
                'common_name' => 'Largetooth sawfish',
                'local_name' => 'Espadang malalaking ngipin',
                'category' => 'sharks_rays',
                'description' => 'The Largetooth Sawfish is a slender-bodied ray with 18–23 evenly spaced teeth starting near the base of its rostrum, a feeble lower caudal fin lobe, and broad-based pectoral fins. It can reach up to 7 meters.',
                'conservation_status' => 'CR',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scalloped hammerhead shark',
                'scientific_name' => 'Sphyrna lewini',
                'common_name' => 'Scalloped hammerhead shark',
                'local_name' => 'Pating na martilyo (kulot)',
                'category' => 'sharks_rays',
                'description' => 'The Scalloped Hammerhead Shark reaches up to 3.5 meters, with a curved head front margin and a median indentation, straight pelvic fin margins, and a low second dorsal fin.',
                'conservation_status' => 'EN',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Great hammerhead shark',
                'scientific_name' => 'Sphyrna mokarran',
                'common_name' => 'Great hammerhead shark',
                'local_name' => 'Pating na martilyo (malaki)',
                'category' => 'sharks_rays',
                'description' => 'The Great Hammerhead Shark has a nearly straight front margin of the head with a median indentation, tall falcate first dorsal fin, and a relatively tall second dorsal fin. It grows up to 5 meters.',
                'conservation_status' => 'EN',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smooth hammerhead shark',
                'scientific_name' => 'Sphyrna zygaena',
                'common_name' => 'Smooth hammerhead shark',
                'local_name' => 'Pating na martilyo (makinis)',
                'category' => 'sharks_rays',
                'description' => 'The Smooth Hammerhead Shark has a curved head front border without a median indentation. It can reach up to 5 meters in length and is less aggressive than other hammerheads.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gray reef shark',
                'scientific_name' => 'Carcharhinus amblyrhynchos',
                'common_name' => 'Gray reef shark',
                'local_name' => 'Abuhing pating sa bahura',
                'category' => 'sharks_rays',
                'description' => 'The Gray Reef Shark grows up to 2.55 meters and is bronze to grey in color, with the first dorsal fin originating over the pectoral fins, and a broad black margin on the caudal fin that becomes less distinct with age.',
                'conservation_status' => 'NT',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oceanic whitetip shark',
                'scientific_name' => 'Carcharhinus longimanus',
                'common_name' => 'Oceanic whitetip shark',
                'local_name' => 'Pating na may puting dulo',
                'category' => 'sharks_rays',
                'description' => 'The Oceanic Whitetip Shark can reach 3.5 meters, recognized by its large, rounded pectoral fins and mottled white-tipped fins; it has an interdorsal ridge and triangular, serrated upper teeth.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blacktip reef shark',
                'scientific_name' => 'Carcharhinus melanopterus',
                'common_name' => 'Blacktip reef shark',
                'local_name' => 'Pating na may itim na dulo',
                'category' => 'sharks_rays',
                'description' => 'The Blacktip Reef Shark grows up to 2 meters, has a short rounded snout, yellowish-brown to grey back, no interdorsal ridge, and striking black tips on the first dorsal and lower caudal fins.',
                'conservation_status' => 'NT',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiger shark',
                'scientific_name' => 'Galeocerdo cuvier',
                'common_name' => 'Tiger shark',
                'local_name' => 'Pating tigre',
                'category' => 'sharks_rays',
                'description' => 'The Tiger Shark can grow up to 6 meters, has a broad blunt head, heavily serrated cockscomb-shaped teeth, and vertical bars along the sides, often fading in sharks over 3 meters.',
                'conservation_status' => 'NT',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Whitetip reef shark',
                'scientific_name' => 'Triaenodon obesus',
                'common_name' => 'Whitetip reef shark',
                'local_name' => 'Pating na puti ang dulo',
                'category' => 'sharks_rays',
                'description' => 'The Whitetip Reef Shark reaches 2 meters and features distinct white tips on its first dorsal and upper caudal fins, a large second dorsal fin, and smooth-edged teeth with large basal cusplets.',
                'conservation_status' => 'NT',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giant manta ray',
                'scientific_name' => 'Manta birostris',
                'common_name' => 'Giant manta ray',
                'local_name' => 'Higanteng pagi',
                'category' => 'sharks_rays',
                'description' => 'The Giant Manta Ray can grow up to 7 meters in disc width, with a dark mouth, dark trailing edges under the pectoral fins, no spots between gill slits, and a T-shaped black and white shoulder patch.',
                'conservation_status' => 'VU',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reef manta ray',
                'scientific_name' => 'Manta alfredi',
                'common_name' => 'Reef manta ray',
                'local_name' => 'Pagi sa bahura',
                'category' => 'sharks_rays',
                'description' => 'The Reef Manta Ray grows up to 5.5 meters wide, has a light-colored mouth, spots between and around the gill slits, a Y-shaped shoulder patch, and no remnant stinging spine.',
                'conservation_status' => 'VU',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Longfin devilray',
                'scientific_name' => 'Mobula eregoodootenkee',
                'common_name' => 'Longfin devilray',
                'local_name' => 'Mahabang-palikpik na pagi',
                'category' => 'sharks_rays',
                'description' => 'The Longfin Devilray reaches a disc width of 1 meter, has a brownish-grey back and white underside with a dark blotch along the front pectoral margins. It has a broad short disc, narrow long head, prominent cephalic lobes, no dorsal spine, and a subterminal mouth with teeth in both jaws.',
                'conservation_status' => 'NT',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spinetail mobula',
                'scientific_name' => 'Mobula japanica',
                'common_name' => 'Spinetail mobula',
                'local_name' => 'Pagi na may tinik sa buntot',
                'category' => 'sharks_rays',
                'description' => 'The Spinetail Mobula has a disc width of 3.1 meters, a bluish-black back with shoulder patches in juveniles, white underside with dark patches in adults, a long tail with a strong spine, and a subterminal mouth with small teeth and black mouth interior.',
                'conservation_status' => 'NT',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shortfin devilray',
                'scientific_name' => 'Mobula kuhlii',
                'common_name' => 'Shortfin devilray',
                'local_name' => 'Maikling-palikpik na pagi',
                'category' => 'sharks_rays',
                'description' => 'The Shortfin Devilray reaches 1.2 meters across, has a dark brown-blue back, white underside with a dark patch along pectoral fins, short cephalic fins, white spot on dorsal fin apex, and a short tail with no spine.',
                'conservation_status' => 'DD',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sicklefin devilray',
                'scientific_name' => 'Mobula tarapacana',
                'common_name' => 'Sicklefin devilray',
                'local_name' => 'Bulinggit na pagi',
                'category' => 'sharks_rays',
                'description' => 'The Sicklefin Devilray can grow up to 3.2 meters wide, with a greyish-black back, white underside with dark pectoral fin edges, narrow falcate disc, short cephalic lobes, slitlike spiracles, and no spine on the tail or dorsal fin.',
                'conservation_status' => 'DD',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smoothtail mobula',
                'scientific_name' => 'Mobula thurstoni',
                'common_name' => 'Smoothtail mobula',
                'local_name' => 'Makinis na buntot na pagi',
                'category' => 'sharks_rays',
                'description' => 'The Smoothtail Mobula reaches a disc width of 2.2 meters, has a dark blue to black back and white underside with dark patches along pectoral fins, concave snout, undulated pectoral fin edges, a white spot on dorsal fin, and a short tail without spine.',
                'conservation_status' => 'NT',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Great white shark',
                'scientific_name' => 'Carcharodon carcharias',
                'common_name' => 'Great white shark',
                'local_name' => 'Puting pating',
                'category' => 'sharks_rays',
                'description' => 'The Great White Shark can grow up to 7.2 meters long, has a fusiform, stout body, serrated triangular teeth, conical snout, large eyes without nictitating membranes, and a crescent-shaped caudal fin.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Basking shark',
                'scientific_name' => 'Cetorhinus maximus',
                'common_name' => 'Basking shark',
                'local_name' => 'Pating-bunganga',
                'category' => 'sharks_rays',
                'description' => 'The Basking Shark, reaching up to 15 meters, has a stout, fusiform body, large ventral mouth extending past the eyes, and five very long gill slits nearly encircling the head. It has a crescent-shaped tail and is considered a vagrant in the Philippines.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tawny nurse shark',
                'scientific_name' => 'Nebrius ferrugineus',
                'common_name' => 'Tawny nurse shark',
                'local_name' => 'Kusing-dagat',
                'category' => 'sharks_rays',
                'description' => 'The Tawny Nurse Shark can grow up to 3.2 meters, with sandy to greyish brown coloration, small eyes, nasal barbels, and large angular dorsal fins. It has a long tail with a subterminal lobe and weak ventral lobe.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Whale shark',
                'scientific_name' => 'Rhincodon typus',
                'common_name' => 'Whale shark',
                'local_name' => 'Butanding',
                'category' => 'sharks_rays',
                'description' => 'The Whale Shark is the largest fish at up to 16 meters, with a fusiform body, 3 dorsal ridges, semi-lunate tail, a flattened head with terminal mouth, and a unique pattern of light spots and stripes on its back.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'White-spotted giant guitarfish',
                'scientific_name' => 'Rhynchobatus australiae',
                'common_name' => 'White-spotted giant guitarfish',
                'local_name' => 'Gitara-pagi',
                'category' => 'sharks_rays',
                'description' => 'This species grows up to 1.87 meters long, has a shark-like body, long stout tail, wedge-shaped head, low angular fins, asymmetrical tail, and yellowish to greenish skin with white spots and dark blotches.',
                'conservation_status' => 'VU',
                'shape' => 'ray-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leopard shark',
                'scientific_name' => 'Stegostoma fasciatum',
                'common_name' => 'Zebra shark / Leopard shark',
                'local_name' => 'Pating-leopardo',
                'category' => 'sharks_rays',
                'description' => 'The Leopard Shark can grow up to 2.35 meters and is yellowish-brown with dark spots. Juveniles have stripes. It has prominent body ridges, a broad head, large rounded pectoral fins, and a long tail almost the size of its body.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue-spotted ribbontail stingray',
                'scientific_name' => 'Taeniura lymma',
                'common_name' => 'Blue-spotted ribbontail stingray',
                'local_name' => 'Pagi na may asul na batik',
                'category' => 'sharks_rays',
                'description' => 'This small ray has a disc width of 0.35 meters, a smooth oval body with blue spots, and a short broad-based tail with blue stripes.',
                'conservation_status' => 'NT',
                'shape' => 'ray-like',
                'is_dangerous' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Megamouth shark',
                'scientific_name' => 'Megachasma pelagios',
                'common_name' => 'Megamouth shark',
                'local_name' => 'Pating-malaking bibig',
                'category' => 'sharks_rays',
                'description' => 'The Megamouth Shark measures between 4.25 to 5.5 meters, has a large cylindrical body, grey top, white underside, a huge terminal mouth extending past the eyes, and dark spots on the lower jaw.',
                'conservation_status' => 'DD',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pelagic thresher shark',
                'scientific_name' => 'Alopias pelagicus',
                'common_name' => 'Pelagic thresher shark',
                'local_name' => 'Pating-aloy',
                'category' => 'sharks_rays',
                'description' => 'The Pelagic Thresher Shark grows up to 3.9 meters, with a dark blue back, white underside, no white patch over pectoral fin bases, long strap-like upper caudal fin lobe almost equal to body length, narrow caudal tip, fusiform body, broad-tipped pectoral fins, narrow head, and moderately large eyes.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Big-eye thresher shark',
                'scientific_name' => 'Alopias superciliosus',
                'common_name' => 'Big-eye thresher shark',
                'local_name' => 'Pating-malaking mata',
                'category' => 'sharks_rays',
                'description' => 'Reaching up to 4.88 meters, the Big-eye Thresher Shark has a purplish gray back, cream undersides, large eyes extending onto the top of the head, curved broad-tipped pectoral fins, and a very long upper caudal fin lobe nearly equal to the rest of the body length.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Common thresher shark',
                'scientific_name' => 'Alopias vulpinus',
                'common_name' => 'Common thresher shark',
                'local_name' => 'Karaniwang pating-aloy',
                'category' => 'sharks_rays',
                'description' => 'The Common Thresher Shark can grow up to 7.6 meters, with a dark blue-grey back, white patch extending over pectoral-fin bases, strap-like upper caudal fin lobe as long or longer than the rest of the body, and small eyes. It has narrow-tipped pectoral and caudal fins and a fusiform body.',
                'conservation_status' => 'VU',
                'shape' => 'shark-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Marine Turtles
            [
                'name' => 'Green turtle',
                'scientific_name' => 'Chelonia mydas',
                'common_name' => 'Green turtle',
                'local_name' => 'pawikan',
                'category' => 'marine_turtles',
                'description' => 'Large sea turtle up to 330 kg with one pair of pre-frontal scales, four lateral, five central, and one claw per foreflipper. Herbivorous, feeding on seagrass and algae. Known to nest in multiple locations across the Philippines including Tubbataha and Turtle Islands.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hawksbill turtle',
                'scientific_name' => 'Eretmochelys imbricata',
                'common_name' => 'Hawksbill turtle',
                'local_name' => 'karahan',
                'category' => 'marine_turtles',
                'description' => 'Weighs up to 80 kg with two pre-frontal scales, overlapping lateral scales, five central scales, and two claws per foreflipper. Critically endangered. Spongivorous diet including sponges, coral, and anemones. Nests in several areas including Davao, Palawan, and Mindoro.',
                'conservation_status' => 'CR',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olive ridley turtle',
                'scientific_name' => 'Lepidochelys olivacea',
                'common_name' => 'Olive ridley turtle',
                'local_name' => 'lunok',
                'category' => 'marine_turtles',
                'description' => 'Small sea turtle up to 50 kg with two pre-frontal scales, six or more lateral scales, and seven or more central scales. Omnivorous diet includes crabs, jellyfish, and small fish. Nests widely in sandy beaches including Davao, Zambales, and Batangas.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Loggerhead turtle',
                'scientific_name' => 'Caretta caretta',
                'common_name' => 'Loggerhead turtle',
                'local_name' => 'bulawon',
                'category' => 'marine_turtles',
                'description' => 'Large turtle reaching up to 180 kg with two pre-frontal scales, five lateral, six central scales, and two claws per flipper. Omnivorous. No nesting recorded in the Philippines, but foraging areas include Albay, Camarines Sur, and Palawan.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leatherback turtle',
                'scientific_name' => 'Dermochelys coriacea',
                'common_name' => 'Leatherback turtle',
                'local_name' => 'balimbing',
                'category' => 'marine_turtles',
                'description' => 'Largest of all turtles, reaching 600 kg and 230 cm. No scales on head or flippers, leathery carapace with seven longitudinal ridges. Gelatinivorous, mainly feeds on jellyfish. Nests in places like Legaspi and Eastern Samar, forages across various regions in the Philippines.',
                'conservation_status' => 'EN',
                'shape' => 'turtle-like',
                'is_dangerous' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
